version: '3'

services:

  author:
    image: grpc-golab-19
    build:
      context: .
    command: /usr/bin/author
    environment:
      AUTHOR_ADDRESS: :4040

  book:
    image: grpc-golab-19
    command: /usr/bin/book
    environment:
      BOOK_ADDRESS: :4041

  compose:
    image: grpc-golab-19
    command: /usr/bin/compose
    environment:
      COMPOSE_ADDRESS: :4042
      COMPOSE_AUTHORTARGET: author:4040
      COMPOSE_BOOKTARGET: book:4041
    ports:
      - 4042:4042

  api:
    image: grpc-golab-19
    command: /usr/bin/api
    environment:
      API_ADDRESS: :8080
      API_COMPOSETARGET: compose:4042
    ports:
      - 8080:8080
