// Code generated by protoc-gen-go. DO NOT EDIT.
// source: book.proto

package book_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetBookRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookRequest) Reset()         { *m = GetBookRequest{} }
func (m *GetBookRequest) String() string { return proto.CompactTextString(m) }
func (*GetBookRequest) ProtoMessage()    {}
func (*GetBookRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{0}
}

func (m *GetBookRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookRequest.Unmarshal(m, b)
}
func (m *GetBookRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookRequest.Marshal(b, m, deterministic)
}
func (m *GetBookRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookRequest.Merge(m, src)
}
func (m *GetBookRequest) XXX_Size() int {
	return xxx_messageInfo_GetBookRequest.Size(m)
}
func (m *GetBookRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookRequest proto.InternalMessageInfo

func (m *GetBookRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetBookResponse struct {
	Book                 *Book    `protobuf:"bytes,1,opt,name=book,proto3" json:"book,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetBookResponse) Reset()         { *m = GetBookResponse{} }
func (m *GetBookResponse) String() string { return proto.CompactTextString(m) }
func (*GetBookResponse) ProtoMessage()    {}
func (*GetBookResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{1}
}

func (m *GetBookResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetBookResponse.Unmarshal(m, b)
}
func (m *GetBookResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetBookResponse.Marshal(b, m, deterministic)
}
func (m *GetBookResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetBookResponse.Merge(m, src)
}
func (m *GetBookResponse) XXX_Size() int {
	return xxx_messageInfo_GetBookResponse.Size(m)
}
func (m *GetBookResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetBookResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetBookResponse proto.InternalMessageInfo

func (m *GetBookResponse) GetBook() *Book {
	if m != nil {
		return m.Book
	}
	return nil
}

type GetAuthorBooksRequest struct {
	AuthorId             int64    `protobuf:"varint,1,opt,name=authorId,proto3" json:"authorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorBooksRequest) Reset()         { *m = GetAuthorBooksRequest{} }
func (m *GetAuthorBooksRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorBooksRequest) ProtoMessage()    {}
func (*GetAuthorBooksRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{2}
}

func (m *GetAuthorBooksRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorBooksRequest.Unmarshal(m, b)
}
func (m *GetAuthorBooksRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorBooksRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthorBooksRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorBooksRequest.Merge(m, src)
}
func (m *GetAuthorBooksRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorBooksRequest.Size(m)
}
func (m *GetAuthorBooksRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorBooksRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorBooksRequest proto.InternalMessageInfo

func (m *GetAuthorBooksRequest) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

type GetAuthorBooksResponse struct {
	Books                []*Book  `protobuf:"bytes,1,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorBooksResponse) Reset()         { *m = GetAuthorBooksResponse{} }
func (m *GetAuthorBooksResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthorBooksResponse) ProtoMessage()    {}
func (*GetAuthorBooksResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{3}
}

func (m *GetAuthorBooksResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorBooksResponse.Unmarshal(m, b)
}
func (m *GetAuthorBooksResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorBooksResponse.Marshal(b, m, deterministic)
}
func (m *GetAuthorBooksResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorBooksResponse.Merge(m, src)
}
func (m *GetAuthorBooksResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuthorBooksResponse.Size(m)
}
func (m *GetAuthorBooksResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorBooksResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorBooksResponse proto.InternalMessageInfo

func (m *GetAuthorBooksResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type Book struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AuthorId             int64    `protobuf:"varint,3,opt,name=authorId,proto3" json:"authorId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_1e89d0eaa98dc5d8, []int{4}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Book) GetAuthorId() int64 {
	if m != nil {
		return m.AuthorId
	}
	return 0
}

func init() {
	proto.RegisterType((*GetBookRequest)(nil), "book.proto.GetBookRequest")
	proto.RegisterType((*GetBookResponse)(nil), "book.proto.GetBookResponse")
	proto.RegisterType((*GetAuthorBooksRequest)(nil), "book.proto.GetAuthorBooksRequest")
	proto.RegisterType((*GetAuthorBooksResponse)(nil), "book.proto.GetAuthorBooksResponse")
	proto.RegisterType((*Book)(nil), "book.proto.Book")
}

func init() { proto.RegisterFile("book.proto", fileDescriptor_1e89d0eaa98dc5d8) }

var fileDescriptor_1e89d0eaa98dc5d8 = []byte{
	// 243 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4a, 0xca, 0xcf, 0xcf,
	0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x42, 0x62, 0x2b, 0x29, 0x70, 0xf1, 0xb9, 0xa7, 0x96,
	0x38, 0xe5, 0xe7, 0x67, 0x07, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97, 0x08, 0xf1, 0x71, 0x31, 0x65,
	0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x31, 0x65, 0xa6, 0x28, 0x99, 0x73, 0xf1, 0xc3,
	0x55, 0x14, 0x17, 0xe4, 0xe7, 0x15, 0xa7, 0x0a, 0xa9, 0x70, 0xb1, 0x80, 0x8c, 0x00, 0x2b, 0xe2,
	0x36, 0x12, 0xd0, 0x43, 0x98, 0xa7, 0x07, 0x56, 0x07, 0x96, 0x55, 0x32, 0xe6, 0x12, 0x75, 0x4f,
	0x2d, 0x71, 0x2c, 0x2d, 0xc9, 0xc8, 0x2f, 0x02, 0x09, 0x17, 0xc3, 0x6c, 0x90, 0xe2, 0xe2, 0x48,
	0x04, 0x8b, 0x7a, 0xc2, 0xec, 0x81, 0xf3, 0x95, 0x1c, 0xb8, 0xc4, 0xd0, 0x35, 0x41, 0x2d, 0x55,
	0xe3, 0x62, 0x05, 0x19, 0x5b, 0x2c, 0xc1, 0xa8, 0xc0, 0x8c, 0xd5, 0x56, 0x88, 0xb4, 0x92, 0x1b,
	0x17, 0x0b, 0x88, 0x8b, 0xee, 0x0f, 0x21, 0x21, 0x2e, 0x96, 0xbc, 0xc4, 0xdc, 0x54, 0x09, 0x26,
	0x05, 0x46, 0x0d, 0xce, 0x20, 0x30, 0x1b, 0xc5, 0x25, 0xcc, 0xa8, 0x2e, 0x31, 0x5a, 0xc5, 0xc8,
	0xc5, 0x0d, 0x32, 0x28, 0x38, 0xb5, 0xa8, 0x2c, 0x33, 0x39, 0x55, 0xc8, 0x89, 0x8b, 0x1d, 0x1a,
	0x0e, 0x42, 0x52, 0xc8, 0x76, 0xa3, 0x06, 0x9f, 0x94, 0x34, 0x56, 0x39, 0xa8, 0x1f, 0xc2, 0xc1,
	0xa1, 0x8d, 0xe4, 0x3b, 0x21, 0x45, 0x34, 0xe5, 0x98, 0xc1, 0x25, 0xa5, 0x84, 0x4f, 0x09, 0xc4,
	0xe0, 0x24, 0x36, 0xb0, 0xac, 0x31, 0x20, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xdf, 0x77, 0x6b, 0xe7,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BookServiceClient is the client API for BookService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BookServiceClient interface {
	GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error)
	GetAuthorBooks(ctx context.Context, in *GetAuthorBooksRequest, opts ...grpc.CallOption) (*GetAuthorBooksResponse, error)
}

type bookServiceClient struct {
	cc *grpc.ClientConn
}

func NewBookServiceClient(cc *grpc.ClientConn) BookServiceClient {
	return &bookServiceClient{cc}
}

func (c *bookServiceClient) GetBook(ctx context.Context, in *GetBookRequest, opts ...grpc.CallOption) (*GetBookResponse, error) {
	out := new(GetBookResponse)
	err := c.cc.Invoke(ctx, "/book.proto.BookService/GetBook", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *bookServiceClient) GetAuthorBooks(ctx context.Context, in *GetAuthorBooksRequest, opts ...grpc.CallOption) (*GetAuthorBooksResponse, error) {
	out := new(GetAuthorBooksResponse)
	err := c.cc.Invoke(ctx, "/book.proto.BookService/GetAuthorBooks", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BookServiceServer is the server API for BookService service.
type BookServiceServer interface {
	GetBook(context.Context, *GetBookRequest) (*GetBookResponse, error)
	GetAuthorBooks(context.Context, *GetAuthorBooksRequest) (*GetAuthorBooksResponse, error)
}

// UnimplementedBookServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBookServiceServer struct {
}

func (*UnimplementedBookServiceServer) GetBook(ctx context.Context, req *GetBookRequest) (*GetBookResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBook not implemented")
}
func (*UnimplementedBookServiceServer) GetAuthorBooks(ctx context.Context, req *GetAuthorBooksRequest) (*GetAuthorBooksResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthorBooks not implemented")
}

func RegisterBookServiceServer(s *grpc.Server, srv BookServiceServer) {
	s.RegisterService(&_BookService_serviceDesc, srv)
}

func _BookService_GetBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.proto.BookService/GetBook",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetBook(ctx, req.(*GetBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BookService_GetAuthorBooks_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorBooksRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BookServiceServer).GetAuthorBooks(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/book.proto.BookService/GetAuthorBooks",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BookServiceServer).GetAuthorBooks(ctx, req.(*GetAuthorBooksRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BookService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "book.proto.BookService",
	HandlerType: (*BookServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetBook",
			Handler:    _BookService_GetBook_Handler,
		},
		{
			MethodName: "GetAuthorBooks",
			Handler:    _BookService_GetAuthorBooks_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "book.proto",
}
