// Code generated by protoc-gen-go. DO NOT EDIT.
// source: compose.proto

package compose_proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetAuthorRequest struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorRequest) Reset()         { *m = GetAuthorRequest{} }
func (m *GetAuthorRequest) String() string { return proto.CompactTextString(m) }
func (*GetAuthorRequest) ProtoMessage()    {}
func (*GetAuthorRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_398975a076140a5e, []int{0}
}

func (m *GetAuthorRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorRequest.Unmarshal(m, b)
}
func (m *GetAuthorRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorRequest.Marshal(b, m, deterministic)
}
func (m *GetAuthorRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorRequest.Merge(m, src)
}
func (m *GetAuthorRequest) XXX_Size() int {
	return xxx_messageInfo_GetAuthorRequest.Size(m)
}
func (m *GetAuthorRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorRequest proto.InternalMessageInfo

func (m *GetAuthorRequest) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetAuthorResponse struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Books                []*Book  `protobuf:"bytes,3,rep,name=books,proto3" json:"books,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetAuthorResponse) Reset()         { *m = GetAuthorResponse{} }
func (m *GetAuthorResponse) String() string { return proto.CompactTextString(m) }
func (*GetAuthorResponse) ProtoMessage()    {}
func (*GetAuthorResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_398975a076140a5e, []int{1}
}

func (m *GetAuthorResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetAuthorResponse.Unmarshal(m, b)
}
func (m *GetAuthorResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetAuthorResponse.Marshal(b, m, deterministic)
}
func (m *GetAuthorResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetAuthorResponse.Merge(m, src)
}
func (m *GetAuthorResponse) XXX_Size() int {
	return xxx_messageInfo_GetAuthorResponse.Size(m)
}
func (m *GetAuthorResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetAuthorResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetAuthorResponse proto.InternalMessageInfo

func (m *GetAuthorResponse) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *GetAuthorResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetAuthorResponse) GetBooks() []*Book {
	if m != nil {
		return m.Books
	}
	return nil
}

type Book struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Book) Reset()         { *m = Book{} }
func (m *Book) String() string { return proto.CompactTextString(m) }
func (*Book) ProtoMessage()    {}
func (*Book) Descriptor() ([]byte, []int) {
	return fileDescriptor_398975a076140a5e, []int{2}
}

func (m *Book) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Book.Unmarshal(m, b)
}
func (m *Book) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Book.Marshal(b, m, deterministic)
}
func (m *Book) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Book.Merge(m, src)
}
func (m *Book) XXX_Size() int {
	return xxx_messageInfo_Book.Size(m)
}
func (m *Book) XXX_DiscardUnknown() {
	xxx_messageInfo_Book.DiscardUnknown(m)
}

var xxx_messageInfo_Book proto.InternalMessageInfo

func (m *Book) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *Book) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*GetAuthorRequest)(nil), "compose.proto.GetAuthorRequest")
	proto.RegisterType((*GetAuthorResponse)(nil), "compose.proto.GetAuthorResponse")
	proto.RegisterType((*Book)(nil), "compose.proto.Book")
}

func init() { proto.RegisterFile("compose.proto", fileDescriptor_398975a076140a5e) }

var fileDescriptor_398975a076140a5e = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0xce, 0xcf, 0x2d,
	0xc8, 0x2f, 0x4e, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x42, 0xe5, 0x2a, 0x29, 0x71, 0x09,
	0xb8, 0xa7, 0x96, 0x38, 0x96, 0x96, 0x64, 0xe4, 0x17, 0x05, 0xa5, 0x16, 0x96, 0xa6, 0x16, 0x97,
	0x08, 0xf1, 0x71, 0x31, 0x65, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0x30, 0x07, 0x31, 0x65, 0xa6,
	0x28, 0x25, 0x71, 0x09, 0x22, 0xa9, 0x29, 0x2e, 0xc8, 0xcf, 0x2b, 0x4e, 0x45, 0x57, 0x24, 0x24,
	0xc4, 0xc5, 0x92, 0x97, 0x98, 0x9b, 0x2a, 0xc1, 0xa4, 0xc0, 0xa8, 0xc1, 0x19, 0x04, 0x66, 0x0b,
	0x69, 0x72, 0xb1, 0x26, 0xe5, 0xe7, 0x67, 0x17, 0x4b, 0x30, 0x2b, 0x30, 0x6b, 0x70, 0x1b, 0x09,
	0xeb, 0xa1, 0xd8, 0xad, 0xe7, 0x94, 0x9f, 0x9f, 0x1d, 0x04, 0x51, 0xa1, 0xa4, 0xc5, 0xc5, 0x02,
	0xe2, 0x12, 0x63, 0xac, 0x51, 0x02, 0x17, 0x9f, 0x33, 0xc4, 0xa0, 0xe0, 0xd4, 0xa2, 0xb2, 0xcc,
	0xe4, 0x54, 0x21, 0x3f, 0x2e, 0x4e, 0xb8, 0x0b, 0x85, 0xe4, 0xd1, 0xac, 0x41, 0xf7, 0x9f, 0x94,
	0x02, 0x6e, 0x05, 0x10, 0xcf, 0x25, 0xb1, 0x81, 0x25, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xba, 0xb0, 0x9a, 0x99, 0x3c, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// ComposeServiceClient is the client API for ComposeService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type ComposeServiceClient interface {
	GetAuthor(ctx context.Context, in *GetAuthorRequest, opts ...grpc.CallOption) (*GetAuthorResponse, error)
}

type composeServiceClient struct {
	cc *grpc.ClientConn
}

func NewComposeServiceClient(cc *grpc.ClientConn) ComposeServiceClient {
	return &composeServiceClient{cc}
}

func (c *composeServiceClient) GetAuthor(ctx context.Context, in *GetAuthorRequest, opts ...grpc.CallOption) (*GetAuthorResponse, error) {
	out := new(GetAuthorResponse)
	err := c.cc.Invoke(ctx, "/compose.proto.ComposeService/GetAuthor", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ComposeServiceServer is the server API for ComposeService service.
type ComposeServiceServer interface {
	GetAuthor(context.Context, *GetAuthorRequest) (*GetAuthorResponse, error)
}

// UnimplementedComposeServiceServer can be embedded to have forward compatible implementations.
type UnimplementedComposeServiceServer struct {
}

func (*UnimplementedComposeServiceServer) GetAuthor(ctx context.Context, req *GetAuthorRequest) (*GetAuthorResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAuthor not implemented")
}

func RegisterComposeServiceServer(s *grpc.Server, srv ComposeServiceServer) {
	s.RegisterService(&_ComposeService_serviceDesc, srv)
}

func _ComposeService_GetAuthor_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAuthorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ComposeServiceServer).GetAuthor(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/compose.proto.ComposeService/GetAuthor",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ComposeServiceServer).GetAuthor(ctx, req.(*GetAuthorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _ComposeService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "compose.proto.ComposeService",
	HandlerType: (*ComposeServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAuthor",
			Handler:    _ComposeService_GetAuthor_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "compose.proto",
}
